name: Quality & Build Check

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Clone Repo
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      # Setup node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # Install all package dependency
      - name: Install dependency
        run: pnpm install --frozen-lockfile

      # Check formatting
      - name: Prettier Check
        run: pnpm format:check

      # Lint
      - name: Eslint Check
        run: pnpm run lint

      # Build dependents
      - name: Build all workspace packages
        run: pnpm -r build

      # Typecheck packages
      - name: Typecheck
        run: pnpm -r typecheck
